### ISSUE TITLE
NullPointer Exception when getting table names

### ISSUE THREAD

**Issue by gschievelbein** [tf-dbis-uni-freiburg/PRoST#37]
I get NullPointer exceptions when querying with version d3152a06bc9ae2597b3260618d4ca40b6edc5e35.

DB is watdiv100k. Attached is a query and the stats file.

By reverting the changed from e5b92813b1d44814a26f9da92989e7d5e2c7a348, 0c37570a595e248b92d0c060fdbf54cd6cb3e02d, and fb63b224f55c1d8f685ce6a9812df83b17eb08a9, I can query without any exceptions. Stats file with changes reverted is watdiv100k_reverted.

Exception in thread "main" java.lang.NullPointerException
        at executor.Utils.toMetastoreName(Utils.java:19)
        at translator.Stats.findTableName(Stats.java:138)
        at translator.Stats.getTableSize(Stats.java:99)
        at translator.Stats.isTableComplex(Stats.java:124)
        at joinTree.PtNode.setIsComplex(PtNode.java:45)
        at joinTree.PtNode.<init>(PtNode.java:39)
        at translator.Translator.createNodes(Translator.java:302)
        at translator.Translator.getNodesQueue(Translator.java:271)
        at translator.Translator.buildTree(Translator.java:111)
        at translator.Translator.translateQuery(Translator.java:81)
        at run.Main.translateSingleQuery(Main.java:236)
        at run.Main.executeBatch(Main.java:244)
        at run.Main.main(Main.java:211)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at 

[files.zip](https://github.com/tf-dbis-uni-freiburg/PRoST/files/2522075/files.zip)

**Comment by polinankoleva** [comment]
Fixed. The reason was wrong stat generated file in the query component.
